# Generated by Django 3.2.16 on 2022-12-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('is_succeded', models.BooleanField(default=False)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useres.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendaand', models.ManyToManyField(to='useres.User')),
                ('meating', models.ManyToManyField(to='meetings.Meeting')),
            ],
        ),
    ]
