# Generated by Django 3.2.16 on 2022-12-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='request_from',
        ),
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
