# Generated by Django 3.2.16 on 2022-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
