# Generated by Django 3.2.16 on 2022-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_at',
            field=models.DateTimeField(null=True),
        ),
    ]
