# Generated by Django 3.2.16 on 2022-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20221216_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
