# Generated by Django 3.2.16 on 2022-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='request_from',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
