# Generated by Django 3.2.16 on 2022-12-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meeting_request_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_at',
            field=models.TimeField(null=True),
        ),
    ]
