# Generated by Django 3.2.16 on 2022-12-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20221216_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meet_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_at',
            field=models.DateField(null=True),
        ),
    ]
