# Generated by Django 3.2.16 on 2022-12-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20221216_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='request_from',
        ),
    ]
