# Generated by Django 3.2.16 on 2022-12-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_remove_meeting_request_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='is_succeded',
            new_name='is_success',
        ),
    ]
