# Generated by Django 3.2.16 on 2022-12-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_order'),
        ('meetings', '0011_rename_is_succeded_meeting_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
