# Generated by Django 3.2.16 on 2022-12-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_step_finished_at'),
        ('meetings', '0012_meeting_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='order',
        ),
        migrations.AddField(
            model_name='meeting',
            name='order',
            field=models.ManyToManyField(null=True, to='project.Project'),
        ),
    ]
