# Generated by Django 3.2.16 on 2022-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_step_is_finished'),
        ('meetings', '0013_auto_20221224_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='order',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
