# Generated by Django 3.2.16 on 2023-02-14 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_step',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b28252db-f481-4059-ac14-2c2e7802ec27'), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='moshtarayet',
            name='uuid',
            field=models.CharField(default=uuid.UUID('222c7b97-b381-49b4-abc3-537a81ac97af'), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f7fd159d-aee9-4061-834d-9848e03e4724'), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e081dc7a-32e8-453f-94d8-9599a458cbc0'), max_length=100, null=True),
        ),
    ]
