# Generated by Django 3.2.16 on 2023-02-14 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_step_show_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cd68cfe9-3a9d-4d76-8652-e5c2d505e3db'), max_length=100, null=True),
        ),
    ]
