# Generated by Django 3.2.16 on 2022-12-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
    ]
