# Generated by Django 3.2.16 on 2023-02-14 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_step',
            name='img',
            field=models.ImageField(null=True, upload_to='steps/images'),
        ),
        migrations.AddField(
            model_name='moshtarayet',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d17b3e45-b8f0-440b-b306-2857e9bd38ed'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8b42e359-3d81-4b77-8e70-314261f32eb1'), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images_step',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b31e8359-1ce3-4830-8118-010b2de13f2d'), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cd21cf62-5b60-4122-92b7-b16a392ccb8e'), max_length=100, null=True),
        ),
    ]
