# Generated by Django 3.2.16 on 2022-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='start_at',
            field=models.DateField(null=True),
        ),
    ]
