# Generated by Django 3.2.16 on 2022-12-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
