# Generated by Django 3.2.16 on 2023-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useres', '0005_alter_user_user'),
        ('project', '0014_auto_20230108_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worker',
            field=models.ManyToManyField(to='useres.User'),
        ),
    ]
