# Generated by Django 3.2.16 on 2023-01-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='12345', max_length=654)),
                ('uuid', models.CharField(default=uuid.uuid1, max_length=350)),
                ('ip', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('location', models.CharField(max_length=120, null=True)),
                ('is_client', models.BooleanField(default=True)),
                ('is_eng', models.BooleanField(default=False)),
                ('is_designer', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
